#!/bin/bash
# you also might need to sudo apt-get install texlive-fonts-extra texinfo

set -e

# Install dependencies for the build to succeed (this list may be incomplete)
Rscript -e "install.packages('knitr') ; install.packages('roxygen2')"

# Make the man pages
Rscript -e "roxygen2::roxygenise()"
R CMD build .

# for checking the package
Rscript -e "install.packages('rmarkdown')"
R CMD check algorithmia_*
